# Generated by Django 2.0.6 on 2018-07-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autre', '0002_article_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='a.jpg', upload_to='testons'),
        ),
    ]
